image: docker:latest
services:
  - docker:dind
stages:
  - build
  - release

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: 'unix:///var/run/docker.sock'

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

tag:image:
  stage: build
  script:
    - docker build --pull --force-rm -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --file Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags

tag:latest:
  stage: release
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CONTAINER_RELEASE_IMAGE
    - docker rmi $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $CI_REGISTRY_IMAGE:latest
  only:
    - tags
